export const EditorTheme = {
    ltr: 'ltr',
    rtl: 'rtl',
    paragraph: 'mb-2 text-web3-text/90 text-lg leading-relaxed relative',
    quote: 'border-l-4 border-web3-textMuted pl-4 italic text-web3-textMuted my-4 text-lg',
    heading: {
        h1: 'text-4xl font-bold text-web3-text mt-8 mb-4 relative group',
        h2: 'text-3xl font-semibold text-web3-text mt-6 mb-3 relative group',
        h3: 'text-2xl font-semibold text-web3-text mt-4 mb-2 relative group',
        h4: 'text-xl font-semibold text-web3-text mt-4 mb-2',
        h5: 'text-lg font-semibold text-web3-text mt-2 mb-1',
        h6: 'text-base font-semibold text-web3-text mt-2 mb-1',
    },
    list: {
        nested: {
            listitem: 'list-none',
        },
        ol: 'list-decimal list-outside ml-6 mb-2 space-y-1',
        ul: 'list-disc list-outside ml-6 mb-2 space-y-1',
        listitem: 'pl-1 leading-relaxed relative',
    },
    image: 'editor-image',
    link: 'text-web3-primary hover:underline cursor-pointer',
    callout: {
        container: 'flex gap-3 rounded-lg p-4 my-3 border [&_.callout-icon]:text-xl [&_.callout-icon]:leading-none [&_.callout-content]:text-web3-text/90 [&_.callout-content_p]:mb-0',
        gray: 'bg-web3-card border-web3-border',
        purple: 'bg-web3-primary/10 border-web3-primary/20',
        pink: 'bg-web3-secondary/10 border-web3-secondary/20',
        cyan: 'bg-web3-accent/10 border-web3-accent/20',
        red: 'bg-red-500/10 border-red-500/20',
        green: 'bg-green-500/10 border-green-500/20',
    },
    // Content visibility when closed is handled natively by <details> - no CSS needed for that.
    collapsibleContainer: 'border border-web3-border rounded-lg my-2 bg-web3-card/30',
    collapsibleTitle: 'flex items-center gap-2 px-3 py-2 cursor-pointer select-none text-web3-text font-medium marker:content-none [&::-webkit-details-marker]:hidden before:content-["▶"] before:text-web3-textMuted before:text-xs [details[open]>&]:before:content-["▼"]',
    collapsibleContent: 'collapsible-content px-3 pb-3 pt-1 border-t border-web3-border/50',
    text: {
        bold: 'font-bold text-web3-text',
        italic: 'italic',
        overflowed: 'editor-text-overflowed',
        hashtag: 'editor-text-hashtag',
        underline: 'underline decoration-web3-primary/30 underline-offset-4',
        strikethrough: 'line-through text-web3-textMuted',
        underlineStrikethrough: 'underline line-through',
        code: 'bg-web3-card border border-web3-border rounded px-1.5 py-0.5 text-sm font-mono text-web3-accent',
    },
    code: 'bg-web3-card/50 border border-web3-border rounded-lg p-4 font-mono text-sm overflow-x-auto my-4 relative',
    codeHighlight: {
        atrule: 'text-purple-400',
        attr: 'text-blue-400',
        boolean: 'text-pink-400',
        builtin: 'text-green-400',
        cdata: 'text-gray-500',
        char: 'text-green-400',
        class: 'text-yellow-400',
        'class-name': 'text-yellow-400',
        comment: 'text-gray-500 italic',
        constant: 'text-pink-400',
        deleted: 'text-red-400',
        doctype: 'text-gray-500',
        entity: 'text-yellow-400',
        function: 'text-blue-400',
        important: 'text-purple-400 font-bold',
        inserted: 'text-green-400',
        keyword: 'text-purple-400',
        namespace: 'text-yellow-400',
        number: 'text-pink-400',
        operator: 'text-gray-400',
        prolog: 'text-gray-500',
        property: 'text-blue-400',
        punctuation: 'text-gray-400',
        regex: 'text-pink-400',
        selector: 'text-green-400',
        string: 'text-green-400',
        symbol: 'text-pink-400',
        tag: 'text-red-400',
        url: 'text-blue-400 underline',
        variable: 'text-yellow-400',
    },
};
